# Generated by Django 6.0.4 on 2026-05-27 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_subscriber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default='Entre your available phone number', max_length=20),
        ),
    ]
