# Generated by Django 6.0.4 on 2026-05-27 14:51
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_subscriber'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE users_user ALTER COLUMN phone_number TYPE varchar(255);",
            reverse_sql="ALTER TABLE users_user ALTER COLUMN phone_number TYPE varchar(20);",
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default='Entre your available phone number', max_length=20),
        ),
    ]