# Generated by Django 6.0.4 on 2026-05-27 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default='07xx xxx xxx', max_length=20),
        ),
        migrations.CreateModel(
            name='SellerSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_display_name', models.CharField(blank=True, max_length=255)),
                ('store_description', models.TextField(blank=True)),
                ('business_location', models.CharField(blank=True, max_length=255)),
                ('support_email', models.EmailField(blank=True, max_length=254)),
                ('support_phone', models.CharField(blank=True, max_length=20)),
                ('default_currency', models.CharField(default='Tsh', max_length=10)),
                ('low_stock_threshold', models.PositiveIntegerField(default=5)),
                ('notify_new_orders', models.BooleanField(default=True)),
                ('notify_verification_updates', models.BooleanField(default=True)),
                ('notify_low_stock', models.BooleanField(default=True)),
                ('notify_admin_messages', models.BooleanField(default=True)),
                ('mobile_money_provider', models.CharField(choices=[('mpesa', 'M-Pesa'), ('tigo_pesa', 'Tigo Pesa'), ('airtel_money', 'Airtel Money'), ('halopesa', 'HaloPesa'), ('other', 'Other')], default='mpesa', max_length=30)),
                ('payout_phone_number', models.CharField(blank=True, max_length=20)),
                ('payout_account_name', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='users.sellerprofile')),
            ],
            options={
                'verbose_name': 'Seller settings',
                'verbose_name_plural': 'Seller settings',
            },
        ),
    ]
