# Generated by Django 6.0.4 on 2026-06-13 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='located_region',
            field=models.CharField(choices=[('ARU', 'Arusha'), ('DSM', 'Dar es salaam'), ('DOM', 'Dodoma'), ('GEITA', 'Geita'), ('IRINGA', 'Iringa'), ('KGR', 'Kagera'), ('KATAVI', 'Katavi'), ('KGM', 'Kigoma'), ('KLM', 'Kilimanjaro'), ('LINDI', 'Lindi'), ('MNYR', 'Manyara'), ('MARA', 'MARA'), ('MBY', 'Mbeya'), ('MORO', 'Morogoro'), ('MTWARA', 'Mtwara'), ('MWNZ', 'Mwanza'), ('NJOMBE', 'Njombe'), ('PWANI', 'Pwani'), ('RUKWA', 'Rukwa'), ('RVM', 'Ruvuma'), ('SHNYNG', 'Shinyanga'), ('SIMIYU', 'Simiyu'), ('SINGIDA', 'Singida'), ('SONGWE', 'Songwe'), ('TABORA', 'Tabora'), ('TANGA', 'Tanga')], default='DSM', max_length=225),
        ),
    ]
