"""
Django settings for exabay project.

Generated by 'django-admin startproject' using Django 6.0.4.
"""

from pathlib import Path

import environ
import dj_database_url


# =============================================================================
# BASE CONFIGURATION
# =============================================================================

BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env(
    DEBUG=(bool, True)
)

environ.Env.read_env(BASE_DIR / ".env")


# =============================================================================
# SECURITY
# =============================================================================

SECRET_KEY = env("SECRET_KEY")

DEBUG = env("DEBUG", default=False)


ALLOWED_HOSTS = [
    "exxabay.com",
    "www.exxabay.com",
    "exxabay.co.tz",
    "www.exxabay.co.tz",
    "127.0.0.1",
    "localhost",
]


# -----------------------------------------------------------------------------
# CSRF
# -----------------------------------------------------------------------------

CSRF_TRUSTED_ORIGINS = [
    "https://exxabay.com",
    "https://www.exxabay.com",
    "https://exxabay.co.tz",
    "https://www.exxabay.co.tz",
]


# =============================================================================
# APPLICATIONS
# =============================================================================

INSTALLED_APPS = [
    "django.contrib.sites",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.humanize",

    "users.apps.UsersConfig",
    "control_panel",
    "products",
    "orders",
    "main",

    "django_filters",
    "storages",

    # Social login
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.google",

    "axes",
]


AUTH_USER_MODEL = "users.User"


# =============================================================================
# MIDDLEWARE
# =============================================================================

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",

    # Redirect .co.tz → .com if this is your intended canonical domain.
    "main.domain_redirect_middleware.RedirectCoTzMiddleware",

    # Serve static files efficiently.
    "whitenoise.middleware.WhiteNoiseMiddleware",

    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",

    "allauth.account.middleware.AccountMiddleware",
    "axes.middleware.AxesMiddleware",
]

AXES_FAILURE_LIMIT = 5
AXES_COOLOFF_TIME = 1

# =============================================================================
# URL / WSGI
# =============================================================================

ROOT_URLCONF = "exabay.urls"

WSGI_APPLICATION = "exabay.wsgi.application"


# =============================================================================
# TEMPLATES
# =============================================================================

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]


# =============================================================================
# DATABASE
# =============================================================================

# DATABASE_URL comes from .env.
#
# Docker:
# postgresql://postgres:PASSWORD@db:5432/exxabay
#
# Local Windows PostgreSQL:
# postgresql://postgres:PASSWORD@localhost:5432/exxabay

if not DEBUG:
    DATABASES = {
        "default": dj_database_url.config(
            conn_max_age=600,
            conn_health_checks=True,
        )
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }

# =============================================================================
# PASSWORD VALIDATION
# =============================================================================

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "UserAttributeSimilarityValidator"
        ),
    },
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "MinimumLengthValidator"
        ),
    },
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "CommonPasswordValidator"
        ),
    },
    {
        "NAME": (
            "django.contrib.auth.password_validation."
            "NumericPasswordValidator"
        ),
    },
]


# =============================================================================
# INTERNATIONALIZATION
# =============================================================================

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# =============================================================================
# STATIC FILES
# =============================================================================

STATIC_URL = "/static/"

STATIC_ROOT = BASE_DIR / "staticfiles"

STATICFILES_DIRS = [
    BASE_DIR / "static",
]


# WhiteNoise production storage.
STORAGES = {
    "default": {
        "BACKEND": "storages.backends.s3.S3Storage",
        "OPTIONS": {
            "location": "media",
        },
    },

    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}


# =============================================================================
# AWS S3 - MEDIA FILES
# =============================================================================

AWS_ACCESS_KEY_ID = env("AWS_ACCESS_KEY_ID")

AWS_SECRET_ACCESS_KEY = env("AWS_SECRET_ACCESS_KEY")

AWS_STORAGE_BUCKET_NAME = env("AWS_STORAGE_BUCKET_NAME")

AWS_S3_REGION_NAME = env("AWS_S3_REGION_NAME")

AWS_S3_FILE_OVERWRITE = False

AWS_DEFAULT_ACL = None

AWS_QUERYSTRING_AUTH = False

AWS_S3_CUSTOM_DOMAIN = (
    f"{AWS_STORAGE_BUCKET_NAME}.s3.{AWS_S3_REGION_NAME}.amazonaws.com"
)


if not DEBUG:
    MEDIA_URL = f"https://{AWS_S3_CUSTOM_DOMAIN}/media/"
else:
    MEDIA_URL = "/media/"


# =============================================================================
# SOCIAL LOGIN
# =============================================================================

SITE_ID = 1


AUTHENTICATION_BACKENDS = [
    "axes.backends.AxesStandaloneBackend",
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
]


LOGIN_REDIRECT_URL = "/"

ACCOUNT_LOGOUT_REDIRECT_URL = "/"

SESSION_COOKIE_AGE = 60 * 60
SESSION_SAVE_EVERY_REQUEST = True


SOCIALACCOUNT_PROVIDERS = {
    "google": {
        "APP": {
            "client_id": env("client_id"),
            "secret": env("secret"),
            "key": "",
        }
    }
}


ACCOUNT_ADAPTER = "users.adapters.ExabayAccountAdapter"

SOCIALACCOUNT_ADAPTER = "users.adapters.ExabaySocialAccountAdapter"


LOGIN_URL = "users:login"

SELLER_DASHBOARD_URL_NAME = "products:sellerDashboard"


# =============================================================================
# EMAIL                                                                        
# =============================================================================

ACCOUNT_AUTHENTICATION_METHOD = "email"

ACCOUNT_EMAIL_REQUIRED = True

ACCOUNT_EMAIL_VERIFICATION = "optional"


EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"

EMAIL_HOST = "smtp.zoho.com"

EMAIL_PORT = 587

EMAIL_USE_TLS = True

EMAIL_HOST_USER = "info@exxabay.com"

EMAIL_HOST_PASSWORD = env("EMAIL_HOST_PASSWORD")

DEFAULT_FROM_EMAIL = "Exxabay <info@exxabay.com>"

SERVER_EMAIL = "info@exxabay.com"


# =============================================================================
# PAYMENT - CLICKPESA
# =============================================================================

CLICKPESA_CLIENT_ID = env("Payment_Client_id")

CLICKPESA_API_KEY = env("PAYMENT_API_KEY")

CLICKPESA_CHECKSUM_KEY = env("CHECKSUM")


# =============================================================================
# PRODUCTION SECURITY
# =============================================================================

# Nginx will terminate HTTPS and forward the request to Gunicorn.
SECURE_PROXY_SSL_HEADER = (
    "HTTP_X_FORWARDED_PROTO",
    "https",
)


# Cookies should only be sent over HTTPS in production.
SESSION_COOKIE_SECURE = not DEBUG

CSRF_COOKIE_SECURE = not DEBUG


# Prevent browsers from MIME-sniffing responses.
SECURE_CONTENT_TYPE_NOSNIFF = True


# Prevent the site from being embedded in frames.
X_FRAME_OPTIONS = "DENY"


# HSTS
#
# Enable this only after HTTPS is working correctly on the domain.
if not DEBUG:
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True


# =============================================================================
# DEFAULT PRIMARY KEY
# =============================================================================

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# =============================================================================
# LOGGING
# =============================================================================

LOGGING = {
    "version": 1,

    "disable_existing_loggers": False,

    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },

    "loggers": {
        "orders": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": True,
        },
    },
}
