# Generated by Django 6.0.4 on 2026-05-23 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminnotification',
            name='notification_type',
            field=models.CharField(choices=[('seller_verified', 'Seller verified'), ('seller_unverified', 'Seller unverified'), ('seller_rejected', 'Seller rejected'), ('seller_message', 'Seller message'), ('buyer_message', 'Buyer message'), ('order_follow_up', 'Order follow-up')], max_length=40),
        ),
    ]
