# Generated by Django 6.0.4 on 2026-05-27 21:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0002_alter_adminnotification_notification_type'),
        ('orders', '0004_payment_gateway_response'),
        ('users', '0004_alter_user_phone_number_sellersettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='TZS', max_length=10)),
                ('phone_number', models.CharField(max_length=20)),
                ('account_name', models.CharField(blank=True, max_length=255)),
                ('order_reference', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(choices=[('previewed', 'Previewed'), ('authorized', 'Authorized'), ('pending', 'Pending'), ('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed'), ('reversed', 'Reversed'), ('refunded', 'Refunded')], default='previewed', max_length=20)),
                ('channel_provider', models.CharField(blank=True, max_length=100)),
                ('clickpesa_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('clickpesa_total_deducted', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('preview_response', models.JSONField(blank=True, null=True)),
                ('gateway_response', models.JSONField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True)),
                ('initiated_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seller_payouts_created', to=settings.AUTH_USER_MODEL)),
                ('order_items', models.ManyToManyField(blank=True, related_name='seller_payouts', to='orders.orderitem')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payouts', to='users.sellerprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
