# Generated by Django 6.0.4 on 2026-05-27 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0003_sellerpayout'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerpayout',
            name='commission_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='sellerpayout',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=5),
        ),
        migrations.AddField(
            model_name='sellerpayout',
            name='gross_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
