# Generated by Django 6.0.4 on 2026-05-29 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_panel', '0004_sellerpayout_commission_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerpayout',
            name='order_reference',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='sellerpayout',
            name='phone_number',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='sellerpayout',
            name='status',
            field=models.CharField(choices=[('previewed', 'Previewed'), ('authorized', 'Authorized'), ('pending', 'Pending'), ('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed'), ('reversed', 'Reversed'), ('refunded', 'Refunded')], default='previewed', max_length=30),
        ),
    ]
