# Generated by Django 6.0.4 on 2026-05-29 19:00
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_payment_gateway_response'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE orders_payment ALTER COLUMN method TYPE varchar(30);",
            reverse_sql="ALTER TABLE orders_payment ALTER COLUMN method TYPE varchar(20);",
        ),
        migrations.RunSQL(
            "ALTER TABLE orders_payment ALTER COLUMN status TYPE varchar(30);",
            reverse_sql="ALTER TABLE orders_payment ALTER COLUMN status TYPE varchar(20);",
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('cod', 'Cash on Delivery'), ('mobile_money', 'Mobile Money')], max_length=30),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=30),
        ),
    ]