# Generated by Django 6.0.4 on 2026-06-26 13:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_payment_method_alter_payment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExxabayGoOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('amount_to_be_paid', models.DecimalField(decimal_places=2, max_digits=12)),
                ('buyer_phone_number', models.CharField(max_length=13)),
                ('order_payment_link', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
