# Generated by Django 6.0.4 on 2026-06-26 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_exxabaygoorder'),
        ('users', '0006_sellerprofile_located_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='exxabaygoorder',
            name='seller_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.sellerprofile'),
        ),
    ]
