# Generated by Django 6.0.4 on 2026-07-04 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_exxabaygoorder_seller_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='exxabaygoorder',
            name='fee_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='exxabaygoorder',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exxabaygoorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='exxabaygoorder',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='exxabaygoorder',
            name='order_payment_link',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
