# Generated by Django 6.0.4 on 2026-07-04 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_exxabaygoorder_fee_amount_exxabaygoorder_paid_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exxabaygoorder',
            name='order_reference',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
