# Generated by Django 6.0.4 on 2026-08-09 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_exxabaygoorder_order_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_control_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
