# Generated by Django 6.0.4 on 2026-04-16 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category_product_category'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='productspecification',
            constraint=models.UniqueConstraint(fields=('product', 'key'), name='unique_product_spec_key'),
        ),
    ]
